server:
  port: 8081
  servlet:
    session:
      timeout: 259200s #session过期时间
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/boutique?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
          mapper : debug
qiniu:
  accessKey:
  secretKey:
  bucket:
  path: