spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boutique?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: mysql
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapping/*.xml
server:
  port: 8080
#showSql