server:
  port: 8081
  servlet:
    session:
      timeout: 259200s #session过期时间
spring:
  datasource:
    username: root
    password: zjh521...
    url: jdbc:mysql://47.106.119.117:3306/Boutique?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 20
      max-wait-millis: 200
  http:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#七牛云配置
qiniu:
  accessKey: r12H00a9wYygK8AtsTYx7TX1m1vrgjVTYrLb4urN
  secretKey: rwuTCmVWrBhsN9rjV1JkAnXGxamSANtkGrNQqL-g
  bucket: boutique
  path: http://pv2vvw8an.bkt.clouddn.com
baseUploadUrl: d://picture/